auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create_new_listing", views.create_new_listing, name="create_new_listing"),
    path("categories", views.categories, name="categories"),
    path("view_category/<int:category>", views.view_category, name="view_category"),
    path("listings/<int:id>", views.view_listing, name="listing"),
    path("watchlist", views.view_watchlist, name="view_watchlist"),
    path("listings/<int:id>/watch", views.add_to_watchlist, name="add_to_watchlist"),
    path("listings/<int:id>/remove", views.remove_from_watchlist, name="remove_from_watchlist"),
    path("listings/<int:id>/place_bid", views.place_bid, name="place_bid"),
    path("listings/<int:id>/close_listing", views.close_listing, name="close_listing")
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    pass


class AuctionListing(models.Model):
    categories = (
        (1, "Fashion"),
        (2, "Toys"),
        (3, "Homeware"),
        (4, "Electronics"),
    )
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=280)
    starting_bid = models.DecimalField(decimal_places=2, max_digits=8)
    image = models.URLField(blank=True)
    category = models.IntegerField(choices=categories, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE, default=3)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return f"{self.name}"


class Bid(models.Model):
    amount = models.DecimalField(decimal_places=2, max_digits=8)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE)
    auction_listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        get_latest_by = "created_at"

    def __str__(self):
        return f"{self.amount}"


class WatchedItem(models.Model):
    auction_listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.auction_listing}"


class Comment(models.Model):
    listing = models.ForeignKey(AuctionListing, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=280)
    time = models.DateTimeField(auto_now_add=True)

auctions/forms.py
from django import forms

categories = (
    (1, "Fashion"),
    (2, "Toys"),
    (3, "Homeware"),
    (4, "Electronics"),
)


class NewListingForm(forms.Form):
    listing_name = forms.CharField(max_length=64)
    description = forms.CharField(widget=forms.Textarea)
    starting_bid = forms.DecimalField(decimal_places=2, initial="0.01")
    image = forms.URLField(required="False")
    category = forms.TypedChoiceField(required="False", choices=categories, coerce=str)

auctions/views.py
from importlib._common import _

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ValidationError
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.db.models import Max

from .models import User, AuctionListing, WatchedItem, Bid, Comment
from .forms import NewListingForm


def index(request):
    auctions = AuctionListing.objects.filter(is_active=True)
    return render(request, "auctions/index.html", {
        "auctions": auctions,
    })


def categories(request):
    categories = AuctionListing.categories
    return render(request, "auctions/categories.html", {
        "categories": categories,
    })


def view_category(request, category):
    auctions = AuctionListing.objects.filter(category=category, is_active=True)
    return render(request, "auctions/view_category.html", {
        "category": category,
        "auctions": auctions,
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")



def create_new_listing(request):
    if request.method == 'POST':
        AuctionListing.objects.create(name=request.POST["listing_name"],
                                      description=request.POST["description"],
                                      starting_bid=request.POST["starting_bid"],
                                      image=request.POST["image"],
                                      category=int(request.POST["category"]))

    return render(request, "auctions/create_new_listing.html", {'form': NewListingForm})


def view_listing(request, id):
    listing = AuctionListing.objects.get(id=id)
    is_active = listing.is_active
    highest_bidder = None
    is_owner = False
    is_watched = False
    if request.user == listing.created_by:
        is_owner = True
    if len(Bid.objects.filter(auction_listing=listing)):
        highest_bid = Bid.objects.filter(auction_listing=listing).latest('created_at')
        highest_bidder = User(id=highest_bid.bidder_id)
    if request.user.is_authenticated:
        is_watched = WatchedItem.objects.filter(auction_listing=listing,
                                                user=request.user)
    current_user = request.user

    comments = Comment.objects.filter(listing=id)
    if request.method == 'POST':
        Comment.objects.create(listing=listing,
                               user=request.user,
                               comment_text=request.POST["comment_text"])
        HttpResponseRedirect(request.META.get('HTTP_REFERER'))

    return render(request, "auctions/listing.html", {
        "listing": listing,
        "is_watched": is_watched,
        "comments": comments,
        "is_owner": is_owner,
        "is_active": is_active,
        "highest_bidder": highest_bidder,
        "current_user": current_user,
    })


def close_listing(request, id):
    listing = AuctionListing.objects.get(id=id)
    if listing.created_by == request.user:
        listing.is_active=False
        listing.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required(login_url="login")
def add_to_watchlist(request, id):
    listing = AuctionListing.objects.get(id=id)
    WatchedItem.objects.create(auction_listing=listing,
                               user=request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required(login_url="login")
def remove_from_watchlist(request, id):
    listing = AuctionListing.objects.get(id=id)
    WatchedItem.objects.filter(auction_listing=listing,
                               user=request.user).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required(login_url="login")
def view_watchlist(request):
    watched_items = WatchedItem.objects.filter(user=request.user)
    return render(request, "auctions/watchlist.html", {
        "watched_items": watched_items,
    })


@login_required(login_url="login")
def place_bid(request, id):
    listing = AuctionListing.objects.get(id=id)
    bid = float(request.POST["bid_amount"])
    bids = Bid.objects.filter(auction_listing=listing)
    if len(bids) != 0:
        current_bid = Bid.objects.filter(auction_listing=listing).latest('created_at')
        if bid > current_bid.amount:
            Bid.objects.create(amount=bid,
                               bidder=request.user,
                               auction_listing=listing)
        else:
            raise ValidationError(_("Bid too low"))
    else:
        starting_bid = listing.starting_bid
        if bid > starting_bid:
            Bid.objects.create(amount=bid,
                               bidder=request.user,
                               auction_listing=listing)
        else:
            raise ValidationError(_("Bid too low"))

    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

auctions/templates/auctions/categories.html
{% extends 'auctions/layout.html' %}

{% block body %}
    <h1>Categories</h1>

    <ul>
        {% for key, value in categories %}
            <a href="{% url 'view_category' key %}" name="{{ key }}"><li>{{ value }}</li></a>
        {% endfor %}
    </ul>


{% endblock %}

auctions/templates/auctions/create_new_listing.html
@login_required

{% extends 'auctions/layout.html' %}

{% block title %}
New Listing
{% endblock %}

{% block body %}
    <h1>Create a New Listing</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>

{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
<h2>Active Listings</h2>

<div class="auction_listings_container">
    {% for auction in auctions %}
    <a href="{% url 'listing' auction.id %}">
        <div class="list_view_container">
            <div>
                <h3>{{ auction.name }}</h3>
                <p>{{ auction.description }}</p>
                <p>The starting bid is: £{{ auction.starting_bid }}</p>
                <p>There are {{ auction.bid_set.count }} bids on this so far.</p>
                {% if auction.bid_set.count > 0 %}
                    <p>The current bid is £{{ auction.bid_set.latest.amount }}</p>
                {% endif %}
            </div>
            {% if auction.image %}
                <img src="{{ auction.image }}" alt="{{ auction.name }}" class="list_image">
            {% else %}
                <img src="https://i.stack.imgur.com/y9DpT.jpg" alt="no image available" class="list_image">
            {% endif %}
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <h1>Auctions</h1>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'view_watchlist' %}">Watchlist</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'create_new_listing' %}">Create a New Listing</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends 'auctions/layout.html' %}

{% block body %}

    <h1>{{ listing.name }}</h1>
    <p>{{ listing.description }}</p>
    <img src="{{ listing.image }}" alt="{{ listing.name }}" class="listed_image">
    <p>Category: {{ listing.get_category_display }}</p>
    <p>Number of bids: {{ listing.bid_set.count }}</p>
    <p>Current bid: £{{ listing.bid_set.latest.amount }}</p>

    {% if user.is_authenticated %}
        {% if is_active %}
            <form action="{% url 'place_bid' listing.id %}" method="POST">
                {% csrf_token %}
                <input type="number" step="0.01" name="bid_amount">
                <input type="submit" value="Place Bid">
            </form>

            {% if is_watched %}
                <form method="POST" action="{% url 'remove_from_watchlist' listing.id %}">
                    {% csrf_token %}
                    <button>Remove from watchlist</button>
                </form>
            {% else %}
                <form method="POST" action="{% url 'add_to_watchlist' listing.id %}">
                    {% csrf_token %}
                    <button>Add to watchlist</button>
                </form>
            {% endif %}

            {% if is_owner %}
                <form method="POST" action="{% url 'close_listing' listing.id%}">
                    {% csrf_token %}
                    <button>Close auction</button>
                </form>
            {% endif %}

        {% else %}
            {% if highest_bidder == current_user %}

                <span>You have won this auction! Congratulations!</span>

            {% else %}

                <span>This auction has now ended. Please search for another auction to participate in.</span>

            {% endif %}

        {% endif %}
    {% endif %}

    <h2>Comments</h2>

    {% for comment in comments %}
        <div>
            <span>{{ comment.user }}</span>
            <span>{{ comment.time }}</span>
            <p>{{ comment.comment_text }}</p>
        </div>
    {% empty %}
        <span>There are no comments yet. Add yours below!</span>
    {% endfor %}
    {% if user.is_authenticated %}
        <h3>Add your comment</h3>
        <form action="" method="POST">
            {% csrf_token %}
            <textarea name="comment_text" id="comment_text" cols="30" rows="10"></textarea>
            <input type="submit" value="Submit comment">
        </form>
    {% else %}
        <span>Please login to add a comment.</span>
    {% endif %}


{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/view_category.html
{% extends 'auctions/layout.html' %}

{% block body %}

<h1>{{ Category }}</h1>
    <div class="auction_listings_container">
        {% for auction in auctions %}
        <a href="{% url 'listing' auction.id %}">
            <div class="list_view_container">
                <div>
                    <h3>{{ auction.name }}</h3>
                    <p>{{ auction.description }}</p>
                    <p>The starting bid is: £{{ auction.starting_bid }}</p>
                    <p>There are {{ auction.bid_set.count }} bids on this so far.</p>
                    {% if auction.bid_set.count > 0 %}
                        <p>The current bid is £{{ auction.bid_set.latest.amount }}</p>
                    {% endif %}
                </div>
                {% if auction.image %}
                    <img src="{{ auction.image }}" alt="{{ auction.name }}" class="list_image">
                {% else %}
                    <img src="https://i.stack.imgur.com/y9DpT.jpg" alt="no image available" class="list_image">
                {% endif %}
            </div>
        </a>
        {% empty %}
        <p>Sorry, there aren't any listings in this category at the moment.</p>
        {% endfor %}
    </div>

{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends 'auctions/layout.html' %}

{% block body %}

<h1>Your watchlist</h1>

<ul>
    {% for item in watched_items %}
        <li><a href="{% url 'listing' item.auction_listing_id %}">{{ item }}</a></li>
    {% empty %}
        <li>There are not currently any items on your watchlist.</li>
    {% endfor %}
</ul>

{% endblock %}